### ISSUE TITLE
Support for `{{format-* ...}}` helpers

### ISSUE THREAD

**Issue by bobisjan** [bobisjan/ember-format#13]

**Comment by bakura10** [comment]
That would be definitely useful!

I want to deeply thank you for this library. I'm currently hacking about FormatJS but it is highly inconvenient to use, your add ons seems to remove all the pain points from using FormatJS!

**Comment by bobisjan** [comment]
I'm going to put my effort on this during the weekend.

You're welcome, I'm glad that the add-on will be helpful!
